"""W4: FIA tree hindcast on real data (Actions): fit the W3 pipeline on first-cycle FIA plots with hindcast climate 1966-1985, score 2005-2024,
compare with observed adult change (fia_observed_change.csv logic). Needs fia_plots.csv.gz from w4-fia and the W1 hindcast tiles."""
import argparse, json, os, time
import numpy as np, pandas as pd
from ctw.species import fia, hindcast as H, hindcast_run as HR, inputs, pipeline as PL

ap = argparse.ArgumentParser()
ap.add_argument("--clim", default="work/clim"); ap.add_argument("--plots", default="work/fia/fia_plots.csv.gz"); ap.add_argument("--out", default="w4-out")
ap.add_argument("--boot", type=int, default=300)
a = ap.parse_args(); os.makedirs(a.out, exist_ok=True); os.environ["W3_CLIM"] = a.clim
src, spec = inputs.climate_source(a.clim)
plots = pd.read_csv(a.plots)
print("plots", len(plots), plots.window.value_counts().to_dict(), flush=True)
species = {nm: sp for sp, nm in fia.PILOT_TREES.items()}
t0 = time.time()
out, fits = HR.hindcast_fia(species, plots, spec, src, cfg=PL.FitConfig(n_jobs=2, check_model=False), n_boot=a.boot, log=lambda *x: print(f"[{time.time() - t0:5.0f}s]", *x, flush=True))
md = ("# FIA tree hindcast, report\n\nFit: first complete inventory cycle per state (median measurement year about 1985) with climate 1966-1985; test: latest complete cycle (about 2019) with climate 2005-2024. "
      "Blocks of 0.5 degree with at least 8 plots in both cycles, rarefied to equal plot numbers. Adult trees (live, 5 inches or more) only: **trees lag climate, so a failure to shift is expected and is not by itself evidence against the model.** "
      "Five trees are far below the 20 species a conclusive group test needs, so every verdict here is illustrative. Generated by ctw/species/w4_fia_hindcast_run.py.\n")
js = {}
def clean(o):
    if isinstance(o, dict): return {str(k): clean(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)): return [clean(v) for v in o]
    if isinstance(o, (np.floating, float)): return None if not np.isfinite(o) else float(o)
    if isinstance(o, np.integer): return int(o)
    if isinstance(o, np.bool_): return bool(o)
    return o
for mode, (res, g, v, cs) in out.items():
    md += "\n" + H.report("fia", f"FIA trees, {mode} variant", res, g, v).replace("\n## ", "\n### ") + "\n"
    js[mode] = dict(group=g, species=res, verdicts=v)
open(f"{a.out}/fia_hindcast_report.md", "w").write(md)
json.dump(clean(js), open(f"{a.out}/fia_hindcast_results.json", "w"), indent=1)
print(md)
