"""W4: GBIF before/after test for the European pilot species (European robin, English oak) from W2's per-species cell tables and target-group grids.
Analysis on 0.5 degree blocks inside the accessible area (within ~330 km of a native presence cell in either period); well-sampled = target group >= 20
records in both periods (ws20). Model: production W3 fit on period-1 cells (target-group density as background), scored under hindcast climate
1966-1985 and 2005-2024 (W1 offers no 1970-1999 / 2000-2020 windows; the offset is documented in docs/pilot/W4-hindcast.md)."""
import argparse, os, sys, time, json
import numpy as np, pandas as pd
from scipy import ndimage
from ctw.species import gbif_split as GS, hindcast as H, hindcast_run as HR, inputs, pipeline as PL, grid

ap = argparse.ArgumentParser()
ap.add_argument("--w2", default="work/w2"); ap.add_argument("--clim", default="work/clim"); ap.add_argument("--out", default="w4-out")
a = ap.parse_args(); os.makedirs(a.out, exist_ok=True); os.environ["W3_CLIM"] = a.clim
SP = {"European robin": ("Erithacus_rubecula", "bird"), "English oak": ("Quercus_robur", "plant")}
src, spec = inputs.climate_source(a.clim)
B = 12
def blocks(g):  # (H, W) -> (H/B, W/B) sums
    return g.reshape(g.shape[0] // B, B, g.shape[1] // B, B).sum((1, 3))
diag = []
sets = {"well": {}, "all": {}}; cv = {}; names = {}; extra = []; n_el = 0; obs_rows = []
t0 = time.time()
for disp, (slug, tgg) in SP.items():
    fc, ft = f"{a.w2}/w2-cells-{slug}.parquet", f"{a.w2}/w2-tg-{tgg}.npz"
    if not (os.path.exists(fc) and os.path.exists(ft)):
        print(disp, "inputs missing", fc, ft, flush=True); continue
    cells = pd.read_parquet(fc)
    if "native_curated" in cells: cells = cells[cells.native_curated.astype(int) == 1] if cells.native_curated.astype(int).sum() else cells
    if "native_wcvp" in cells and tgg == "plant": cells = cells[cells.native_wcvp.astype(int) != 0]
    z = np.load(ft); g = z[z.files[0]]
    print(disp, "cells", len(cells), "tg grid", g.shape, flush=True)
    p1_tg, p2_tg = blocks(g[1].astype(np.int64)), blocks(g[2].astype(np.int64))
    pc1, pc2 = cells[cells.n_1970_1999 > 0], cells[cells.n_2000_2020 > 0]
    pres_blocks = np.zeros(p1_tg.shape, bool)
    for d in (pc1, pc2): pres_blocks[d.row.values // B, d.col.values // B] = True
    access = ndimage.binary_dilation(pres_blocks, iterations=6)
    br, bc = np.nonzero(access & (p1_tg > 0) & (p2_tg > 0))
    tg = pd.DataFrame(dict(group=tgg, row=np.r_[br * B, br * B], col=np.r_[bc * B, bc * B], year=np.r_[np.full(len(br), 1985), np.full(len(br), 2010)],
                           n=np.r_[p1_tg[br, bc], p2_tg[br, bc]]))
    occ = pd.concat([pd.DataFrame(dict(species=disp, row=pc1.row.values, col=pc1.col.values, year=1985)),
                     pd.DataFrame(dict(species=disp, row=pc2.row.values, col=pc2.col.values, year=2010))])
    # model: production fit on period-1 presence cells
    dens = g[1].astype(np.float32)
    fit = HR.fit_window1(disp, spec, src, pc1.row.values, pc1.col.values, density=dens, group=tgg, cfg=PL.FitConfig(n_jobs=2, check_model=False), log=lambda *x: print(*x, flush=True))
    cb = tg.drop_duplicates(["row", "col"])
    sc = HR.score_cells(fit, src, cb.row.values + B // 2, cb.col.values + B // 2)
    diag.append(f"{disp}: tg layer sums {[int(g[i].sum()) for i in range(g.shape[0])]}, nonzero cells {[int((g[i] > 0).sum()) for i in range(g.shape[0])]}, tg blocks p1>0 {int((p1_tg > 0).sum())} p2>0 {int((p2_tg > 0).sum())}, "
                f"accessible {int(access.sum())}, usable blocks {len(br)}, score cells {len(sc)}, finite score cells {int(np.isfinite(sc.score1).sum()) if len(sc) else 0}, cellset sizes well/all computed next")
    print(disp, "accessible blocks with tg in both periods:", len(br), "score cells:", len(sc), "presence cells p1/p2:", len(pc1), len(pc2),
          "well-sampled blocks:", len(GS.well_sampled(tg, tgg)), flush=True)
    for variant, wo in (("well", True), ("all", False)):
        cs = GS.species_cellset(occ, tg, disp, tgg, well_only=wo, scores=sc, thr=fit.thr)
        sets[variant][disp] = cs
    m = fit.cv["metrics"].get("gbm", {}); cv[disp] = dict(tss=m.get("tss", np.nan), auc=m.get("auc", np.nan))
    n_el += int(len(pc1) >= 20 and len(pc2) >= 20)
    gap = GS.effort_gap(sets["well"][disp], sets["all"][disp]); extra.append((disp, gap, len(pc1), len(pc2)))
    o = H.observed_change(sets["well"][disp], n_boot=300)
    obs_rows.append(dict(species=disp, **{k: o[k] for k in ("km", "km_lo", "km_hi", "bearing", "north", "north_se", "edge_hi_km", "edge_lo_km", "area_change", "detectable")}, n_cells=len(sets["well"][disp].lat)))
    print(disp, "done", "%.0fs" % (time.time() - t0), flush=True)
md = "# GBIF before and after: European species\n\nPeriods 1970-1999 and 2000-2020, 0.5 degree blocks, well sampled = target group at least 20 records in both periods. Climate: hindcast windows 1966-1985 and 2005-2024 (offset documented). Generated by ctw/species/w4_gbif_run.py.\n"
for variant in ("well", "all"):
    if not sets[variant]: continue
    res, gv, vd = H.run_test(sets[variant], "gbif", cv=cv, n_eligible=n_el, n_boot=300)
    md += "\n" + H.report("gbif", f"GBIF split, {'well-sampled blocks' if variant == 'well' else 'all blocks with target-group records in both periods'}", res, gv, vd).replace("\n## ", "\n### ") + "\n"
md += "\n## Effort-bias gap (well-sampled versus all blocks)\n\n| species | presence cells p1 / p2 | blocks well / all | shift km well / all | northward km well / all |\n|---|---|---|---|---|\n"
for d, gp, n1, n2 in extra:
    md += f"| {d} | {n1} / {n2} | {gp['n_well']} / {gp['n_all']} | {gp['well_km']:.0f} / {gp['all_km']:.0f} | {gp['well_north']:.0f} / {gp['all_north']:.0f} |\n"
md += "\n## Diagnostics\n\n" + "\n".join("- " + d for d in diag) + "\n"
open(f"{a.out}/gbif_split_report.md", "w").write(md); print(md)
