"""W4: full BBS hindcast on real data (Actions). Needs the W1 hindcast tiles (hind_1966-1985, hind_2005-2024 for the North American tiles) in --clim and
the BBS files from w4-bbs (release species-pilot-data). Fits the W3 pipeline on window 1 only, scores window 2 and writes the report."""
import argparse, json, os, sys, time
import numpy as np, pandas as pd
from ctw.species import bbs, hindcast as H, hindcast_run as HR, inputs, pipeline as PL

ap = argparse.ArgumentParser()
ap.add_argument("--clim", default="work/clim"); ap.add_argument("--bbs", default="work/bbs"); ap.add_argument("--out", default="w4-out")
ap.add_argument("--species", default="data/species/w4/bbs_validation_species.csv"); ap.add_argument("--only", default="")
ap.add_argument("--recommended", type=int, default=1); ap.add_argument("--boot", type=int, default=300); ap.add_argument("--block", type=int, default=1)
a = ap.parse_args(); os.makedirs(a.out, exist_ok=True)
os.environ["W3_CLIM"] = a.clim
src, spec = inputs.climate_source(a.clim)
routes_fit = pd.read_csv(f"{a.bbs}/bbs_routes_fit.csv"); routes_q = pd.read_csv(f"{a.bbs}/bbs_route_cells.csv")
det = pd.read_csv(f"{a.bbs}/bbs_presence_long.csv.gz")
pres = det if "p1" in det else bbs.route_presence(det)
sp = pd.read_csv(a.species)
if a.recommended: sp = sp[sp.recommended]
if a.only: sp = sp[sp.sci.isin(a.only.split(","))]
species = {r.english: int(r.AOU) for r in sp.itertuples()}
print(len(species), "species", flush=True)
cfg = PL.FitConfig(n_jobs=2, check_model=False)
t0 = time.time()
results, g, verdicts, cellsets, fits = HR.hindcast_bbs(species, routes_fit, routes_q, pres, spec, src, cfg=cfg, block=a.block, n_boot=a.boot,
                                                       log=lambda *x: print(f"[{time.time() - t0:5.0f}s]", *x, flush=True))
md = "# BBS hindcast, first report\n\nFit window 1966-1985 (BBS routes, W3 pipeline), test window 2005-2024. Generated by ctw/species/w4_hindcast_run.py.\n\n" + \
     H.report("bbs", "North American Breeding Bird Survey", results, g, verdicts) + "\n"
open(f"{a.out}/bbs_hindcast_report.md", "w").write(md)
def clean(o):
    if isinstance(o, dict): return {k: clean(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)): return [clean(v) for v in o]
    if isinstance(o, (np.floating, float)): return None if not np.isfinite(o) else float(o)
    if isinstance(o, (np.integer,)): return int(o)
    if isinstance(o, (np.bool_,)): return bool(o)
    return o
json.dump(clean(dict(group=g, species=results, verdicts=verdicts)), open(f"{a.out}/bbs_hindcast_results.json", "w"), indent=1)
print(md)
